### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by fdabl** [kywk/hexo-theme_casper#2]
Hey kywk!

Just started using hexo and trying different layouts out on my localhost. I found that when I hit the site with your layout, I get a TypeError in casper/head.ejs on line 35:

<% if (config.feed.type = 'atom') { %>
_Cannot set property 'type' of undefined_

On way to fix this is to have the user npm install hexo-generator-feed and than edit the main _config file to put feed stuff in there.

On a more user friendly approach, I suggest you change both the if (config.feed.type = 'atom') and if (config.feed.type ='rss') conditionals to:

if (config.feed && config.feed.type == 'atom')
if (config.feed && config.feed.type == 'rss')

This way you first check if config.feed is undefined, avoiding a TypeError if it is indeed.

cheers

**Comment by kywk** [comment]
hi dostodabsi,
Yes, you are right, thanks.
