### ISSUE TITLE
Gravatar

### ISSUE THREAD

**Issue by alexandre** [kywk/hexo-theme_casper#4]
Hail,

I would like to use Gravatar to update my logo... can anyone think someway to do it?
Current, I use this:

``` node
_config.yml:

logo: //pt.gravatar.com/userimage/28012198/dfcb56791d001388e1eb7c0b2c06196d.png
```

[ ]'s

**Comment by kywk** [comment]
I think you can calculate your gravatar hash code, the gravatar image request url will like 

```
logo:  //www.gravatar.com/avatar/HASH
```

[Gravatar - Globally Recognized Avatars](http://goo.gl/n8MJoQ), FYI.

**Comment by alexandre** [comment]
Thanks, Kywk! =]
